In [25]:
#importing packages
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

#read the csv
df = pd.read_csv("AdultData.csv",sep = None, engine = 'python',header = None, decimal = '.', names = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country','income' ]  )
#read the columns 
df.dtypes
#checking the count of the columns
df.count()
#checking age range first
dfAge = df['age']
dfAgeRangeCheck = dfAge.between(16,100)
dfAgeRangeCheck[dfAgeRangeCheck[:] == False]
#no value that is outside of range 16 and 100
#Next to check the workclass
df['workclass'].value_counts()
#number of missing values
mv=1836
#remove whitespace
df['workclass']=df['workclass'].str.strip()
#total counts of dataset
df.count()
#calculate the percentage of missing values
p = (1836.0/32561)
#p=0.056 which means only 5.6% values have missed. It is very insignificant, so we will drop them
df = df[df["workclass"] != "?" ]
# we can see that there are a few missing values
#Next is fnlwgt
dfFinalWeight = df['fnlwgt']
df[df['fnlwgt'].isnull()]
#continuous variable with no nulls
#Next is education
dfEducation = df['education']
dfEducation.value_counts()
#check No nulls
df[dfEducation.isnull()]
#no nulls next is education-num
dfEducationNum = df['education-num']
dfEducationNum.value_counts()
#no null variables
#Next is marital-status
dfMaritalStatus = df['marital-status']
dfMaritalStatus.value_counts()
#no missing variables. Onto occupation
df['occupation'].value_counts()
#total number of missing values
mv=mv+7
#remove whitespace
df['occupation']=df['occupation'].str.strip()
#total counts of dataset
df.count()
#calculate the percentage of missing values
p = (7.0/30725)
#p=0.00022 which means only 5.6% values have missed. It is very insignificant, so we will drop them
df = df[df["occupation"] != "?" ]
#next is relationship
dfRelationship = df['relationship']
dfRelationship.value_counts()
#no missing values,
#next we move onto race
dfRace = df['race']
dfRace.value_counts()
#no missing values, so onto the next variable 
dfSex = df['sex']
dfSex.value_counts()
#no missing variables, so onto the next of capital-gain 0 or above
dfCapitalGain = df['capital-gain']
dfCapitalGainCheck = dfCapitalGain.between(0,999999)
dfCapitalGainCheck[dfCapitalGainCheck[:] == False]
#capital-loss check 0 or above
dfCapitalLoss = df['capital-loss']
dfCapitalLossCheck = dfCapitalLoss.between(0,999999)
dfCapitalLossCheck[dfCapitalLossCheck[:] == False]
#checking if hours per week is at least 0 and above
dfHoursPerWeek = df['hours-per-week']
dfHoursPerWeekCheck = dfHoursPerWeek.between(0,9999999)
dfHoursPerWeekCheck[dfHoursPerWeekCheck[:] == False]
#checking native countries, 556 records of '?' values
df['native-country'].value_counts()
#total number of missing values
mv=mv+556
#remove whitespace
df['native-country']=df['native-country'].str.strip()
#total counts of dataset, total records is 30178
df.count()
#calculate the percentage of missing values
p = (556.0/30178)
#p=0.0184 which means only 5.6% values have missed. It is very insignificant, so we will drop them
df = df[df["native-country"] != "?" ]
print(df.head(5))


   age         workclass  fnlwgt   education  education-num  \
0   39         State-gov   77516   Bachelors             13   
1   50  Self-emp-not-inc   83311   Bachelors             13   
2   38           Private  215646     HS-grad              9   
3   53           Private  234721        11th              7   
4   28           Private  338409   Bachelors             13   

        marital-status         occupation    relationship    race      sex  \
0        Never-married       Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse    Exec-managerial         Husband   White     Male   
2             Divorced  Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse  Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse     Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week native-country  income  
0          2174             0              40  United-States   <=50K  
1         

In [26]:
"""from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
#df['incomeNum'] = df['income'].map({'<=50K': 0, '>50k': 1})
#y_attribute_variable = df.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13]]
#x_target_variable = df.iloc[:,[14]]
#x = df.iloc[:,[1]]
#need to encode into numbers 



#data preprocessing 
#td = preprocessing.LabelEncoder()
#x_target_variable = td.fit_transform(x_target_variable)
#print x_target_variable
#<=50k is 0 and >50k is 1



#splitting the data to 50% test and 50% training set
#x_train, x_test, y_train, y_test = train_test_split(y_attribute_variable,x_target_variable , test_size =0.5)



#strategic splits of the data 
#clf = DecisionTreeClassifier(criterion = 'gini')

#train the attributes
#fit = clf.fit(x_train, y_train)



#using pandas.get_dummies
#give the columns of the categorical data
#cat_columns = {"workclass", 'education'}
#df_processed = pd.get_dummies(df,columns = cat_columns)
#print(df_processed)

"""

'from sklearn.tree import DecisionTreeClassifier\nfrom sklearn.model_selection import train_test_split\nfrom sklearn import preprocessing\nfrom sklearn.preprocessing import OneHotEncoder\n#df[\'incomeNum\'] = df[\'income\'].map({\'<=50K\': 0, \'>50k\': 1})\n#y_attribute_variable = df.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11,12,13]]\n#x_target_variable = df.iloc[:,[14]]\n#x = df.iloc[:,[1]]\n#need to encode into numbers \n\n\n\n#data preprocessing \n#td = preprocessing.LabelEncoder()\n#x_target_variable = td.fit_transform(x_target_variable)\n#print x_target_variable\n#<=50k is 0 and >50k is 1\n\n\n\n#splitting the data to 50% test and 50% training set\n#x_train, x_test, y_train, y_test = train_test_split(y_attribute_variable,x_target_variable , test_size =0.5)\n\n\n\n#strategic splits of the data \n#clf = DecisionTreeClassifier(criterion = \'gini\')\n\n#train the attributes\n#fit = clf.fit(x_train, y_train)\n\n\n\n#using pandas.get_dummies\n#give the columns of the categorical data\n#cat_colum

In [32]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

X = df.iloc[:,[0,1,3,4,5,6,7,8,9,12,13]].values
Z = pd.DataFrame(X)
Z
#T = df.iloc[:,[14]]

"""X is 10 columns
Age, workclass, education, education-num, marital-status, 
occupation, relationship, race, sex, hours-per-week, native-country,
"""
#import labelencoder and onehotencoder for categorical variables
#to numerical
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
#column workclass
X[:,1] = labelencoder_X.fit_transform(X[:,1])
#column education
X[:,2] = labelencoder_X.fit_transform(X[:,2])
#column education-num
X[:,3] = labelencoder_X.fit_transform(X[:,3])
#column marital-status
X[:,4] = labelencoder_X.fit_transform(X[:,4])
#column occupation
X[:,5] = labelencoder_X.fit_transform(X[:,5])
#column relationship
X[:,6] = labelencoder_X.fit_transform(X[:,6])
#column race
X[:,7] = labelencoder_X.fit_transform(X[:,7])
#column sex
X[:,8] = labelencoder_X.fit_transform(X[:,8])
#column native-country
X[:,10] = labelencoder_X.fit_transform(X[:,10])

X
Z = pd.DataFrame(X)

feature_cols = [0,1,2,3,4,5,6,7,8,9,10]
A = Z[feature_cols]

#B = Z[11]
#A=A.astype('int')
B = df['income']


# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(A, B, test_size=0.5, random_state=0)
clf = DecisionTreeClassifier()

fit = clf.fit(X_train, y_train)
y_pre = fit.predict(X_test)



from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pre)
print cm

from sklearn.metrics import classification_report
print classification_report(y_test, y_pre)





       0  1   2   3  4   5  6  7  8   9   10
0      39  5   9  12  4   0  1  4  1  40  38
1      50  4   9  12  2   3  0  4  1  13  38
2      38  2  11   8  0   5  1  4  1  40  38
3      53  2   1   6  2   5  0  2  1  40  38
4      28  2   9  12  2   9  5  2  0  40   4
5      37  2  12  13  2   3  5  4  0  40  38
6      49  2   6   4  3   7  1  2  0  16  22
7      52  4  11   8  2   3  0  4  1  45  38
8      31  2  12  13  4   9  1  4  0  50  38
9      42  2   9  12  2   3  0  4  1  40  38
10     37  2  15   9  2   3  0  2  1  80  38
11     30  5   9  12  2   9  0  1  1  40  18
12     23  2   9  12  4   0  3  4  0  30  38
13     32  2   7  11  4  11  1  2  1  50  38
14     34  2   5   3  2  13  0  0  1  45  25
15     25  4  11   8  4   4  3  4  1  35  38
16     32  2  11   8  4   6  4  4  1  40  38
17     38  2   1   6  2  11  0  4  1  50  38
18     43  4  12  13  0   3  4  4  0  45  38
19     40  2  10  15  2   9  0  4  1  60  38
20     54  2  11   8  5   7  4  2  0  20  38
21     35 

In [7]:

from sklearn.datasets import load_iris

iris = load_iris()

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state = 0)

clf = DecisionTreeClassifier()

fit = clf.fit(X_train, y_train)
y_pre = fit.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pre)
print cm

from sklearn.metrics import classification_report
print classification_report(y_test, y_pre)



[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

   micro avg       0.97      0.97      0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



In [1]:
"""
from sklearn import tree


with open("iris_new.dot", 'w') as f:
    f = tree.export_graphviz(clf, out_file=f,feature_names = ['age', 'workclass',  'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex','hours-per-week', 'native-country'] , class_names = df['income'], filled = True, rounded = True, special_characters = True)
tree.export_graphviz(clf) 


render('dot', 'png', 'iris_new.dot')  
"""


'\nfrom sklearn import tree\n\n\nwith open("iris_new.dot", \'w\') as f:\n    f = tree.export_graphviz(clf, out_file=f,feature_names = [\'age\', \'workclass\',  \'education\', \'education-num\', \'marital-status\', \'occupation\', \'relationship\', \'race\', \'sex\',\'hours-per-week\', \'native-country\'] , class_names = df[\'income\'], filled = True, rounded = True, special_characters = True)\ntree.export_graphviz(clf) \n\n\nrender(\'dot\', \'png\', \'iris_new.dot\')  \n'